[tool.poetry]
name = "encord"
version = "0.1.44"
description = "Encord Python SDK Client"
authors = ["Cord Technologies Limited <hello@encord.com>"]
license = "Apache Software License"
keywords = ["encord"]
packages = [
    { include = "encord"},
]
readme = "README.md"
repository="https://github.com/encord-team/encord-client-python"
documentation="https://python.docs.encord.com/"
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.11"
python-dateutil = "^2.8.2"
requests = "^2.28.2"
cryptography = "^40.0.1"
tqdm = "^4.65.0"
Shapely = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = 'encord\/.*'

[tool.isort]
# setting isort to a compatibility mode with `black`
# https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
profile = "black"

[tool.pylint.'MASTER']
ignore = "tests"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = "all"
enable = "C0123, C0200, C0209, E0401, E0602, E1101, E1205, W0611, W0621, W1309, W1404, W1514"
