name: "Setup test environment"
description: "Sets up Python, Poetry and dependencies"

inputs:
  python:
    description: "Python version to use"
    default: 3.9.14
    required: false
  poetry:
    description: "Poetry version to use"
    default: 1.7.0
    required: false
  environment-location:
    description: "Environment location"
    required: false
    default: '.'
  cache-key:
    description: "Cache key"
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python }}

    - uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.project }}/.venv
        key: ${{inputs.cache-key}}

    - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.environment-location }}
        poetry lock --no-update
        poetry install --no-interaction
        source .venv/bin/activate
      shell: bash
