name: SDK PR report

on:
  pull_request:
    branches:
      - master

env:
  PYTHON: 3.8
  POETRY: 1.5.0
  UNIT_TEST_REPORT: unit-test-report.xml

concurrency:
  group: cord-client-${{ github.ref }}-pr
  cancel-in-progress: true

jobs:
  formatting:
    name: Linting and type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup root poetry environment
        uses: ./.github/actions/setup-root-poetry-environment
      - name: Run linting, type checking and testing
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--all-files --hook-stage=push"

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON }}

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY }}
          virtualenvs-in-project: true

      - name: Check cache
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: unit-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON }}-1

      - name: Install dependencies
        if: $${{ steps.cached-poetry.outputs.cache-hit != 'true' }}
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run python -m pytest tests --verbose --junitxml=${{ env.UNIT_TEST_REPORT }}

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.UNIT_TEST_REPORT }}
          path: ${{ env.UNIT_TEST_REPORT }}

      - name: Publish unit test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{ env.UNIT_TEST_REPORT }}
          check_name: Unit test report
