name: SDK PR report

on:
  pull_request:
    branches:
      - master

env:
  PYTHON: 3.8
  POETRY: 1.7.0
  UNIT_TEST_REPORT_PYTHON_3_8_P1: unit-test-report-python-3_8_p1.xml
  UNIT_TEST_REPORT_PYTHON_3_8_P2: unit-test-report-python-3_8_p2.xml
  BACKEND_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  BACKEND_REPO: cord-team/cord-backend

concurrency:
  group: cord-client-${{ github.ref }}-pr
  cancel-in-progress: true

jobs:
  formatting:
    name: Linting and type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup root poetry environment
        uses: ./.github/actions/setup-root-poetry-environment
      - name: Run linting, type checking and testing
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--all-files --hook-stage=push"

  unit-tests-python-3-8:
    name: Run unit tests (Python 3.8, Pydantic 1.x)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run unit tests for Python 3.8
        uses: ./.github/actions/run-unit-tests
        with:
          python-version: 3.8.16
          test-report-file: ${{ env.UNIT_TEST_REPORT_PYTHON_3_8_P1 }}

  unit-tests-python-3-8-pydantic-2:
    name: Run unit tests (Python 3.8, Pydantic 2.x)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run unit tests for Python 3.8
        uses: ./.github/actions/run-unit-tests
        with:
          python-version: 3.8.16
          pydantic-version: 2.6.1
          test-report-file: ${{ env.UNIT_TEST_REPORT_PYTHON_3_8_P2 }}

  integration-tests-python-3-11:
    name: Run integration tests for Python 3.11
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.BACKEND_REPO }}
          token: ${{ env.BACKEND_ACCESS_TOKEN }}
          path: encord-backend

      - name: Run integration tests for Python 3.11
        uses: ./.github/actions/run-integration-tests
        with:
          python-version: 3.11.2
          integration-tests-location: ./encord-backend/projects/sdk-integration-tests
          test-report-file: ${{ env.INTEGRATION_TEST_REPORT_PYTHON_3_11 }}
          private-key: ${{ env.INTEGRATION_TESTS_PRIVATE_KEY }}
          sdk-repository-url: https://github.com/encord-team/encord-client-python@${{ github.sha }}
